version: '3.3'
services:
  webgl:
    image: inclusionnarino/game:1.0.8
    container_name: inclusion-narino-game
    ports:
      - "8090:80"
    networks:
      - inclusion-narino-network
    depends_on:
      - back
    restart: always
    volumes:
      - "./docker/serverdata.json:/webgl/StreamingAssets/serverdata.json"
  front:
    image: inclusionnarino/front:1.0.8
    container_name: inclusion-narino-front
    ports: 
      - "3000:3000"
    networks:
      - inclusion-narino-network
    depends_on:
      - back
    restart: always
    environment:
      - NEXT_PUBLIC_API_URL=http://my.content:3001
      - NEXT_PUBLIC_GAME_URL=http://my.content:8090/
  back:
    image: inclusionnarino/back:1.3.1
    container_name: inclusion-narino-back
    ports:
      - "3001:3001"
    networks:
      - inclusion-narino-network
    restart: always
    environment:
      - DB_HOST=my.content
      - DB_PORT=3306
      - DB_USER=narino-user
      - DB_PASSWORD=Inclusionnarino2022*
      - DB_NAME=talentum_inclusion_narino
      - DOCKER_DEPLOYMENT=true
networks:
  inclusion-narino-network:
    driver: bridge